version: '2'
services:
  ros-core:
    image: gramaziokohler/ros-ur-planner:20.11
    container_name: ros-core
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-ur-planner:20.11
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-core:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: gramaziokohler/ros-ur-planner:20.11
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-core:11311
    depends_on:
      - ros-core
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  moveit-demo:
    image: gramaziokohler/ros-ur-planner:20.11
    container_name: moveit-demo
    environment:
      - ROS_HOSTNAME=moveit-demo
      - ROS_MASTER_URI=http://ros-core:11311
      - DISPLAY=gui:0.0
    depends_on:
      - ros-core
      - gui
    command:
      - roslaunch
      - --wait
      - ur5_moveit_config
      - demo.launch

  gui:
    image: gramaziokohler/novnc:latest
    ports:
      - "8080:8080"
