name: swinburne
channels:
    - conda-forge

dependencies:
   - python=3.8
   - pip
   - git
   - compas=1.*
   - compas_fab>=0.18.3
   - igl>=2.2.1
   - compas_cgal>=0.1.2
   - compas_rrc
   - compas_slicer
